CREATE TABLE IF NOT EXISTS usuario (
    id BIGINT(20)  generated by default as identity PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    senha VARCHAR(150) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);



INSERT INTO usuario (nome, email, senha) VALUES ('ADMINISTRADOR', 'admin@softplan.com', '123' );
INSERT INTO usuario (nome, email, senha) VALUES ('TRIADOR', 'triador@softplan.com', '123' );
INSERT INTO usuario (nome, email, senha) VALUES ('FINALIZADOR', 'triador@softplan.com', '123' );
