CREATE TABLE IF NOT EXISTS processo (
	id BIGINT(20) generated by default as identity PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
    	descricao VARCHAR(200) NOT NULL
);

INSERT INTO processo (nome, descricao) VALUES ('PROCESSO DE COMPRA', 'PROCESSO DE AQUISIÇÃO DE PRODUTOS');
INSERT INTO processo (nome, descricao) VALUES ('PROCESSO DE VENDA', 'PROCESSO DE VENDA DE PRODUTOS');
INSERT INTO processo (nome, descricao) VALUES ('PROCESSO DE ESTORNO', 'PROCESSO DE ESTORNO DE VALORES');
INSERT INTO processo (nome, descricao) VALUES ('PROCESSO DEVOLUTIVO', 'PROCESSO DE DEVOLUÇÃO DE PRODUTOS');

CREATE TABLE IF NOT EXISTS parecer (
    id_usuario BIGINT(20) NOT NULL,
    id_processo BIGINT(20) NOT NULL,
    descricao VARCHAR(200) NOT NULL,
        
    PRIMARY KEY (id_usuario, id_processo),
    FOREIGN KEY (id_usuario) REFERENCES usuario(id),
    FOREIGN KEY (id_processo) REFERENCES processo(id)
);


INSERT INTO parecer (id_usuario, id_processo, descricao) VALUES (3, 1, 'A COMPRA PODE SER EFETUADA SEM LICITAÇÃO');

